fengines:
    chans_per_packet: 96
    snap01:
        ants: [0, 32]
        gbe: '10.41.0.101'
        source_port: 10000
    snap03:
        ants: [32, 64]
        gbe: '10.41.0.102'
        source_port: 10000
    snap04:
        ants: [64, 96]
        gbe: '10.41.0.103'
        source_port: 10000
    snap05:
        ants: [96, 128]
        gbe: '10.41.0.104'
        source_port: 10000
    snap06:
        ants: [128, 160]
        gbe: '10.41.0.105'
        source_port: 10000
    snap07:
        ants: [160, 192]
        gbe: '10.41.0.106'
        source_port: 10000
    snap08:
        ants: [192, 224]
        gbe: '10.41.0.107'
        source_port: 10000
    snap09:
        ants: [224, 256]
        gbe: '10.41.0.108'
        source_port: 10000
    snap10:
        ants: [256, 288]
        gbe: '10.41.0.109'
        source_port: 10000
    snap11:
        ants: [288, 320]
        gbe: '10.41.0.110'
        source_port: 10000
    snap12:
        ants: [320, 352]
        gbe: '10.41.0.111'
        source_port: 10000

xengines:
  arp:
    # lwa-gpu01
    10.41.0.18: 0x043f72d0b10e
    10.41.0.34: 0x043f72d0b112
    # lwa-gpu02
    10.41.0.17: 0x043f72d0b116
    10.41.0.33: 0x043f72d0b106
    # lwa-gpu03
    10.41.0.19: 0x043f72d0b0f6
    10.41.0.35: 0x043f72d0b0e2
    # lwa-gpu04
    10.41.0.20: 0x043f72ab3750
    10.41.0.36: 0x043f72dfc1f4
    # lwa-gpu05
    10.41.0.21: 0x043f72dfc2a0
    10.41.0.37: 0x043f72dfc2e4
    # lwa-gpu06
    10.41.0.22: 0x043f72dfc2e8
    10.41.0.38: 0x043f72dfc1d4
    # lwa-gpu07
    10.41.0.23: 0x043f72dfc2d8
    10.41.0.39: 0x043f72dfc308
    # lwa-gpu08
    10.41.0.24: 0x043f72dfc2a8
    10.41.0.40: 0x043f72dfc300
  chans:
    # lwa-gpu01
    10.41.0.18-10000: [1024, 1120]
    10.41.0.18-20000: [1120, 1216]
    10.41.0.34-10000: [1216, 1312]
    10.41.0.34-20000: [1312, 1408]
    # lwa-gpu02
    10.41.0.17-10000: [1408, 1504]
    10.41.0.17-20000: [1504, 1600]
    10.41.0.33-10000: [1600, 1696]
    10.41.0.33-20000: [1696, 1792]
    # lwa-gpu04
    10.41.0.20-10000: [1792, 1888]
    10.41.0.20-20000: [1888, 1984]
    10.41.0.36-10000: [1984, 2080]
    10.41.0.36-20000: [2080, 2176]
    # lwa-gpu05
    10.41.0.21-10000: [2176, 2272]
    10.41.0.21-20000: [2272, 2368]
    10.41.0.37-10000: [2368, 2464]
    10.41.0.37-20000: [2464, 2560]
    # lwa-gpu06
    10.41.0.22-10000: [2560, 2656]
    10.41.0.22-20000: [2656, 2752]
    10.41.0.38-10000: [2752, 2848]
    10.41.0.38-20000: [2848, 2944]
    # lwa-gpu07
    10.41.0.23-10000: [2944, 3040]
    10.41.0.23-20000: [3040, 3136]
    10.41.0.39-10000: [3136, 3232]
    10.41.0.39-20000: [3232, 3328]
    # lwa-gpu08
    10.41.0.24-10000: [3328, 3424]
    10.41.0.24-20000: [3424, 3520]
    10.41.0.40-10000: [3520, 3616]
    10.41.0.40-20000: [3616, 3712]

